__version__ = "0.1"
__author__ = "Ryan Baten"
__title__ = "manim_interactive_scene"
__license__ = "MIT License"
__description__ = "Package for using interactive manim scenes and scene checkpointing."
